import { withTranslations } from "@/commons/utils/withTranslations";
import Head from "next/head";
import { useTranslation } from "next-i18next";

export const getStaticProps = withTranslations();

export default function Home() {
  const { t } = useTranslation();
  return (
    <>
      <Head>
        <title>{t("headTitle")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      hi
    </>
  );
}
